=== Flavelloni/XML/task2_SecretSocialML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- ############################## -->
  <!-- Root -->
  <xs:element name="secretSocialML">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="user"/>
        <xs:element ref="society"/>
      </xs:choice>
    </xs:complexType>
    
    <xs:unique name="uniqueUser">
      <xs:selector xpath="user"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    
    <xs:unique name="uniqueSociety">
      <xs:selector xpath="society"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    
  </xs:element>
  
  <!-- ############################## -->
  <!-- Users -->
  <xs:element name="user">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="sex" type="sexString"/>
        <xs:element name="dateOfBirth" type="xs:date"/>
        <xs:element ref="friends"/>
        <xs:element ref="societies"/>
        <xs:element name="profession" minOccurs="0" type="xs:string"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>

  </xs:element>
    
    
  <!-- -->
  <xs:simpleType name="sexString">
    <xs:restriction base="xs:string">
      <xs:enumeration value="m"/>
      <xs:enumeration value="f"/>
    </xs:restriction>
  </xs:simpleType>
   
  <xs:element name="friends" type="friendList">      
    <xs:unique name="uniqueFriends">
      <xs:selector xpath="userID"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>
  
  <xs:complexType name="friendList">
    <xs:sequence>
      <xs:element name="userID" minOccurs="0" maxOccurs="unbounded" type="xs:positiveInteger"/>      
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="societies" type="socIDList">
    <xs:unique name="uniqueSocieties">
      <xs:selector xpath="socID"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>
  
  <xs:complexType name="socIDList">
    <xs:sequence>
      <xs:element name="socID" minOccurs="0" maxOccurs="unbounded" type="xs:positiveInteger"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <!-- ############################## -->
  <!-- Societies -->
  <xs:element name="society">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element ref="members"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="members" type="memberList">
    <xs:unique name="uniqueMembers">
      <xs:selector xpath="userID"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>
  
  
  <!-- ############################## -->
  <xs:complexType name="memberList">
    <xs:sequence>
      <xs:element name="userID" minOccurs="0" maxOccurs="unbounded" type="xs:positiveInteger"/>      
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:attribute name="id" type="xs:positiveInteger"/>
  
</xs:schema>

=== Flavelloni/XML/SecretSocialML.xml
<?xml version="1.0" encoding="UTF-8"?>
<secretSocialML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="task2_SecretSocialML.xsd">
    
    <!-- Users -->
    <user id="1">
        <name>Johnnyboy 123</name>
        <sex>m</sex>
        <dateOfBirth>1987-01-01</dateOfBirth>
        <friends>
            <userID>2</userID>
            <userID>3</userID>
        </friends>
        <societies>
            <socID>1</socID>
            <socID>2</socID>
        </societies>
        <profession>Software Engineer</profession>
    </user>
    <user id="2">
        <name>Tom Turbo</name>
        <sex>m</sex>
        <dateOfBirth>1987-01-02</dateOfBirth>
        <friends>
            <userID>1</userID>
        </friends>
        <societies>
            <socID>1</socID>
        </societies>
    </user>
    <user id="3">
        <name>Jack</name>
        <sex>m</sex>
        <dateOfBirth>1987-01-03</dateOfBirth>
        <friends>
            <userID>1</userID>
            <userID>4</userID>
        </friends>
        <societies>
            <socID>2</socID>
        </societies>
    </user>
    <user id="4">
        <name>Anna</name>
        <sex>f</sex>
        <dateOfBirth>1987-01-04</dateOfBirth>
        <friends>
            <userID>3</userID>
        </friends>
        <societies/>
    </user>
    
    
    <!-- Societies -->
    <society id="1">
        <name>Fight Club</name>
        <description>We fight illegally</description>
        <members>
            <userID>1</userID>
            <userID>2</userID>
        </members>
    </society>
    <society id="2">
        <name>Gamble Club</name>
        <description>We gamble illegally</description>
        <members>
            <userID>1</userID>
            <userID>3</userID>
        </members>
    </society>
</secretSocialML>
